# Dependencies
#markdown:            redcarpet
highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Chris Diana
tagline:             'Blog & Tutorials'
url:                 blog.chrisdianamedia.com
baseurl:
paginate:            10

# About/contact
author:
  name:              Chris Diana
  url:               https://chrisdianamedia.com
  email:             cdiana.media@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:             https://github.com/cdmedia/blog
